import Head from 'next/head'
import tw from 'twin.macro'

const Home = () => {
  return (
    <>
      <Head>
        <title>Anime Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <MainText>[ Insert app here ]</MainText>
      </Container>
    </>
  )
}

export default Home

const Container = tw.main`flex items-center justify-center p-8 w-screen h-screen`

const MainText = tw.h1`text-xl`
